export default {
	ADD_MESSAGE: 'ADD_MESSAGE',
    ADD_MESSAGES: 'ADD_MESSAGES',
    CLEAR_MESSAGES:'CLEAR_MESSAGES',

    FORGOT_PASSWORD_MESSAGE: 'FORGOT_PASSWORD_MESSAGE',
    RESET_PASSWORD_MESSAGE: 'RESET_PASSWORD_MESSAGE',
	UNSUBSCRIBE_MESSAGE: 'UNSUBSCRIBE_MESSAGE',
    COMMON_MESSAGE: 'COMMON_MESSAGE',
}
